; RORY_FACE_OPTIMISED.Z80
;
; Map Source File.
;
; Info:
;   Section       : rory face map
;   Bank          : 0
;   Map size      : 20 x 18
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Tiles\Story-tiles\rory_face_tileset_optimised.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 46
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "rory face map", ROM0

rory_face:
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$62,$64,$67,$2C
DB $6D,$6E,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$63,$66,$68,$6A
DB $6F,$70,$72,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$65,$6B,$69,$6C
DB $3B,$71,$73,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2E,$30,$36,$38
DB $3E,$40,$45,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2F,$31,$37,$39
DB $3F,$41,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$32,$34,$3A,$3C
DB $42,$43,$46,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$33,$35,$74,$3D
DB $2B,$44,$47,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$49,$4F,$51
DB $57,$59,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$48,$4A,$50,$52
DB $58,$5A,$5F,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$4B,$4D,$53,$55
DB $5B,$5D,$60,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$4C,$5C,$5C,$5C
DB $5C,$5E,$61,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C
DB $2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C,$2C

; End of RORY_FACE_OPTIMISED.Z80
