; KNIGHT_TILESET.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Knight scene tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 42
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Knight scene tiles", ROM0

; Start of tile array.
knight_tileset:
DB $07,$FF,$07,$FF,$07,$FF,$07,$FF
DB $03,$FF,$01,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$07,$FF
DB $C0,$FF,$E0,$FF,$F0,$FF,$F8,$FF
DB $FC,$FF,$FE,$FF,$FE,$FF,$3F,$FF
DB $1F,$FF,$3F,$FF,$7F,$FF,$7F,$FF
DB $7F,$FF,$7F,$FF,$FF,$FF,$7F,$FF
DB $07,$FF,$07,$FF,$03,$FF,$01,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$01,$FF,$03,$FF,$07,$FF
DB $BF,$FF,$DF,$FF,$EF,$FF,$FF,$FF
DB $FF,$FF,$7F,$FF,$3F,$FF,$3F,$FF
DB $3F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $07,$FF,$0F,$FF,$1F,$FF,$3F,$FF
DB $7F,$FF,$FF,$FF,$FE,$FF,$F8,$FF
DB $F0,$FF,$F8,$FF,$FC,$FF,$FC,$FF
DB $FC,$FF,$FC,$FF,$FE,$FF,$FC,$FF
DB $C0,$FF,$C0,$FF,$C0,$FF,$C0,$FF
DB $80,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$E0,$FF
DB $F9,$FF,$F0,$FF,$E0,$FF,$F0,$FF
DB $F8,$FF,$F8,$FF,$F8,$FF,$F8,$FF
DB $F8,$FF,$FE,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $F8,$FF,$FE,$FF,$3F,$FF,$3F,$FF
DB $1F,$FF,$1F,$FF,$0F,$FF,$0F,$FF
DB $0F,$FF,$1F,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$9F,$FF,$C0,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$18,$FF
DB $F8,$FF,$FC,$FF,$FF,$FF,$7F,$FF
DB $3F,$FF,$3F,$FF,$1F,$FF,$0F,$FF
DB $1F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
DB $3F,$FF,$7F,$FF,$FF,$FF,$7F,$FF
DB $3E,$FF,$7F,$FF,$7F,$FF,$7F,$FF
DB $7F,$FF,$7F,$FF,$3F,$FF,$3F,$FF
DB $3F,$FF,$1F,$FF,$1F,$FF,$1F,$FF
DB $0F,$FF,$07,$FF,$03,$FF,$03,$FF
DB $3F,$FF,$9F,$FF,$CF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $7E,$FF,$FE,$FF,$FE,$FF,$FC,$FF
DB $F8,$FF,$F8,$FF,$F0,$FF,$E0,$FF
DB $F0,$FF,$F8,$FF,$F8,$FF,$F8,$FF
DB $F8,$FF,$FC,$FF,$FE,$FF,$FC,$FF
DB $F8,$FF,$F0,$FF,$E0,$FF,$F0,$FF
DB $F8,$FF,$FC,$FF,$FE,$FF,$FE,$FF
DB $FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF
DB $FC,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$80,$FF,$C0,$FF
DB $1F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
DB $3F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
DB $1F,$FF,$1E,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $C0,$FF,$F8,$FF,$FC,$FF,$FD,$FF
DB $FD,$FF,$FF,$FF,$FF,$FF,$7F,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$07,$FF,$0F,$FF,$1F,$FF
DB $3F,$FF,$1F,$FF,$3F,$FF,$7F,$FF
DB $7F,$FF,$7F,$FF,$7F,$FF,$7F,$FF
DB $7F,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$FF,$7E,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FD,$FF,$FC,$FF,$FC,$FF,$FC,$FF
DB $FC,$FF,$FC,$FF,$FC,$FF,$F8,$FF
DB $00,$FF,$00,$FF,$00,$FF,$80,$FF
DB $C0,$FF,$C0,$FF,$C0,$FF,$C0,$FF
DB $80,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $F0,$FF,$E0,$FF,$F0,$FF,$FB,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FD,$FF,$FE,$FF
DB $FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$FF,$00,$FF,$00,$FF,$80,$FF
DB $80,$FF,$00,$FF,$80,$FF,$E0,$FF
DB $F8,$FF,$FE,$FF,$FF,$FF,$7F,$FF
DB $1F,$FF,$0F,$FF,$C0,$FF,$E0,$FF
knight_tileset_end: 

; End of KNIGHT_TILESET.Z80
