; MUSHROOM_ATTACK_SCENE_OPTIMIZED.Z80
;
; Map Source File.
;
; Info:
;   Section       : ROM0
;   Bank          : 0
;   Map size      : 32 x 19
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Tiles\Story-tiles\knights_tiles_optimised.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 46
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "Knight intro background", ROM0

knights_intro:
; Compressed data: 
DB $7C, $2A, $01, $2E, $01, $30, $01, $36, $01, $38, 
DB $01, $2A, $01, $3F, $01, $45, $01, $2A, $01, $4A, 
DB $01, $4C, $01, $51, $01, $53, $08, $2A, $01, $2F, 
DB $01, $31, $01, $37, $01, $39, $01, $2A, $01, $40, 
DB $01, $46, $01, $2A, $01, $4B, $01, $4D, $01, $52, 
DB $01, $54, $08, $2A, $01, $32, $01, $34, $01, $3A, 
DB $01, $3C, $01, $41, $01, $43, $01, $47, $02, $2A, 
DB $01, $4F, $01, $55, $01, $57, $08, $2A, $01, $33, 
DB $01, $35, $01, $3B, $01, $3D, $01, $42, $01, $44, 
DB $01, $48, $01, $49, $01, $4E, $01, $50, $01, $56, 
DB $01, $58, $A4, $2A

; End of MUSHROOM_ATTACK_SCENE_OPTIMIZED.Z80
