; RORY_FACE_BLINK_TILESET.Z80
;
; Tile Source File.
;
; Info:
;   Section              : rory face tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 70
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "rory face blink tiles", ROM0

; Start of tile array.
rory_face_bl_tileset:
DB $80,$FF,$80,$FF,$F0,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $01,$C1,$03,$C3,$1E,$DE,$F0,$FE
DB $F1,$FF,$F0,$FE,$FC,$FE,$F3,$FF
DB $EC,$FF,$8B,$FF,$8C,$FC,$80,$FC
DB $80,$F0,$80,$E0,$80,$E0,$80,$E0
DB $F0,$FF,$C0,$FF,$C0,$FF,$C0,$FF
DB $C0,$FF,$E0,$FF,$F0,$FF,$FC,$FF
DB $F0,$FF,$C0,$FF,$C0,$FF,$C0,$FF
DB $FC,$FF,$FE,$FF,$FE,$FF,$FF,$FF
DB $00,$E0,$00,$C0,$00,$C0,$00,$C0
DB $00,$C0,$20,$A0,$7F,$FF,$00,$C0
DB $00,$C0,$00,$80,$00,$00,$00,$00
DB $00,$00,$00,$80,$00,$C0,$80,$C0
DB $00,$00,$00,$00,$1F,$1F,$60,$60
DB $80,$80,$00,$00,$E0,$E0,$20,$E0
DB $C0,$C0,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FC,$FC,$FC,$FC,$FF,$FF,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$01,$01,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$01,$01,$01,$01
DB $00,$00,$FC,$FC,$78,$78,$00,$00
DB $00,$00,$00,$00,$F8,$F8,$04,$04
DB $00,$00,$00,$00,$C0,$C0,$20,$20
DB $00,$01,$31,$31,$58,$79,$46,$7F
DB $33,$3F,$1C,$1F,$07,$07,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $38,$7F,$07,$7F,$07,$FF,$0F,$FF
DB $0F,$FF,$9F,$FF,$5F,$FF,$3F,$FF
DB $BF,$FF,$5F,$FF,$9F,$FF,$0F,$7F
DB $0F,$1F,$0F,$1F,$07,$0F,$07,$0F
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$03,$03,$FC,$FC
DB $00,$0F,$00,$0F,$00,$00,$00,$01
DB $00,$01,$20,$21,$F0,$F1,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$01
DB $00,$03,$00,$0F,$01,$1F,$07,$3F
DB $0F,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$7F,$FF,$1F,$FF,$1F,$FF
DB $3F,$FF,$7F,$FF,$1F,$FF,$1F,$FF
DB $0F,$FF,$0F,$7F,$0F,$7F,$1F,$FF
DB $7F,$FF,$7F,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FE,$FF,$FC,$FF,$FC,$FE,$F8,$FE
DB $C0,$F8,$F8,$F8,$FC,$FC,$FF,$FF
DB $FF,$FF,$FF,$FF,$C2,$C3,$84,$C7
DB $84,$C7,$88,$CF,$08,$8F,$10,$9F
DB $10,$9F,$20,$3F,$21,$3E,$7D,$7E
DB $F8,$FE,$F8,$FE,$F0,$FE,$F0,$FC
DB $F1,$FD,$F1,$FD,$E1,$FD,$E1,$F9
DB $E1,$F9,$E1,$F9,$C3,$FB,$C3,$F3
DB $C3,$F3,$83,$F3,$83,$E3,$83,$83
DB $7F,$7F,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$C0,$C0
DB $FF,$FF,$80,$F0,$C0,$F8,$30,$FE
DB $3C,$CF,$7F,$83,$7F,$80,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$1E,$1E,$1E,$1A,$1F,$11
DB $3F,$20,$FF,$C0,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$C0,$FF,$FC,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$00,$FF,$00,$FF,$80,$FF,$C0
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$00,$00,$01,$01,$01,$0F,$0F
DB $F3,$FF,$01,$1F,$03,$3F,$FF,$FF
DB $FC,$03,$FC,$03,$FE,$01,$FE,$01
DB $FE,$01,$FE,$01,$FF,$00,$FF,$00
DB $1F,$7F,$7F,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$1F,$1F
DB $83,$9F,$41,$CF,$40,$CF,$40,$CF
DB $40,$C7,$40,$C3,$20,$E3,$20,$E3
DB $FF,$00,$FF,$00,$FF,$00,$FF,$07
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $20,$E1,$10,$F0,$F0,$F0,$F0,$F0
DB $F0,$F0,$F0,$F0,$F8,$F8,$F8,$F8
DB $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8
DB $F8,$F8,$F8,$F8,$FC,$FC,$FC,$FC
DB $FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF
DB $7F,$FF,$7F,$FF,$7F,$FF,$7F,$FF
DB $3F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
DB $3F,$7F,$1F,$3F,$1F,$3F,$1F,$3F
DB $1F,$3F,$1F,$3F,$1F,$3F,$0F,$7F
DB $0F,$7F,$0F,$7F,$0F,$7F,$0F,$7F
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FC,$FF,$F0,$FF,$C0,$FF,$C0,$FF
DB $C0,$FF,$C0,$FF,$80,$FF,$80,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$00,$F0
DB $80,$FF,$80,$FF,$80,$FF,$80,$FF
DB $80,$FF,$80,$FF,$80,$FF,$80,$FF
DB $00,$E0,$00,$C0,$00,$C0,$00,$C0
DB $00,$80,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $1F,$1F,$0F,$0F,$07,$07,$07,$07
DB $03,$03,$03,$03,$03,$03,$03,$03
DB $03,$03,$01,$01,$81,$81,$01,$01
DB $01,$01,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$01,$01
DB $01,$01,$01,$81,$01,$81,$01,$81
DB $FF,$FF,$FE,$FE,$FE,$FE,$FE,$FE
DB $FE,$FE,$FC,$FC,$FC,$FC,$FC,$FC
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FC,$FC
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$03,$7F
DB $E0,$E0,$C0,$C0,$80,$80,$80,$80
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$3F,$00,$1F,$00,$0F,$00,$0F
DB $00,$07,$00,$03,$00,$03,$00,$03
DB $00,$01,$80,$81,$40,$41,$40,$41
DB $40,$41,$40,$43,$40,$47,$40,$47
DB $FF,$FF,$3F,$FF,$0F,$FF,$0F,$FF
DB $0F,$FF,$0F,$FF,$07,$FF,$07,$FF
DB $07,$FF,$07,$FF,$07,$FF,$07,$FF
DB $07,$FF,$07,$FF,$07,$FF,$07,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$03,$03
rory_face_bl_tileset_end:

; End of RORY_FACE_BLINK_TILESET.Z80
