; RK_STORY_SCREEN_CASTLE.Z80
;
; Map Source File.
;
; Info:
;   Section       : 0
;   Bank          : 0
;   Map size      : 32 x 19
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Tiles\Story-tiles\rk_castle_tiles.asm
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 44
;   Split data    : No
;
; This file was generated by GBMB v1.8

titleScreenWidth  EQU 32
titleScreenHeight EQU 19
titleScreenBank   EQU 0

SECTION "Castle background", ROM0

story_castle: 
; Compressed data: 
DB $98, $2A, $86, $29, $98, $2A, $86, $29, $98, $2A, 
DB $06, $29, $58, $29, $58, $29, $58, $29, $98, $2A, 
DB $86, $29, $98, $2A, $86, $29, $91, $2A, $02, $61, 
DB $69, $65, $83, $2A, $86, $29, $90, $2A, $04, $61, 
DB $62, $29, $66, $67, $82, $2A, $86, $29, $8F, $2A, 
DB $01, $68, $62, $82, $29, $01, $66, $67, $81, $2A, 
DB $06, $29, $58, $29, $58, $29, $58, $29, $8E, $2A, 
DB $01, $61, $62, $84, $29, $02, $66, $67, $2A, $86, 
DB $29, $8D, $2A, $02, $60, $5F, $5D, $85, $29, $01, 
DB $64, $65, $86, $29, $8F, $2A, $00, $59, $84, $29, 
DB $81, $2A, $00, $6A, $81, $6B, $81, $29, $00, $6C, 
DB $81, $6B, $8F, $2A, $01, $5E, $5C, $8D, $29, $90, 
DB $2A, $01, $59, $58, $8C, $29, $90, $2A, $00, $59, 
DB $8D, $29, $90, $2A, $01, $5E, $5C, $8C, $29, $91, 
DB $2A, $00, $59, $8C, $29, $91, $2A, $00, $59, $8C, 
DB $29, $91, $2A, $00, $59, $8C, $29, $8F, $2A, $00, 
DB $5A, $83, $5B, $8A, $29, $5C
story_castle_end: 

