; RK_BLACK_BACKGROUND.Z80
;
; Map Source File.
;
; Info:
;   Section       : 0
;   Bank          : 0
;   Map size      : 32 x 19
;   Tile set      : rk_story_tiles.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 43
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "Black background", ROM0

rk_black_background: 
; Compressed data: 
DB $FF, $29, $FF, $29, $FF, $29, $FF, $29, $DF, $29