; RK_TEXT_BOX.Z80
;
; Map Source File.
;
; Info:
;   Section       : 0
;   Bank          : 0
;   Map size      : 32 x 19
;   Tile set      : rk_story_tiles.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 43
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "Text box", ROM0

textBox:
; Compressed data: 
DB $FF, $2C, $FF, $2C, $E7, $2C