; RORY_FACE_DETERMINED_OPTIMISED.Z80
;
; Map Source File.
;
; Info:
;   Section       : rory face det map
;   Bank          : 0
;   Map size      : 20 x 18
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Tiles\Story-tiles\rory_face_determined_tileset_optimised.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 46
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "rory face det map", ROM0

rory_face_determined:
; Compressed data: 
DB $C1, $29, $05, $61, $63, $66, $29, $6C, $6D, $8D, 
DB $29, $06, $62, $65, $67, $69, $6E, $6F, $71, $8C, 
DB $29, $06, $64, $6A, $68, $6B, $2C, $70, $72, $8C, 
DB $29, $06, $2E, $30, $36, $38, $3D, $3F, $44, $8C, 
DB $29, $05, $2F, $31, $37, $39, $3E, $40, $8D, $29, 
DB $06, $32, $34, $3A, $3B, $41, $42, $45, $8C, $29, 
DB $06, $33, $35, $73, $3C, $74, $43, $46, $8D, $29, 
DB $04, $48, $4E, $50, $56, $58, $8D, $29, $06, $47, 
DB $49, $4F, $51, $57, $59, $5E, $8C, $29, $06, $4A, 
DB $4C, $52, $54, $5A, $5C, $5F, $8C, $29, $00, $4B, 
DB $83, $5B, $01, $5D, $60, $D6, $29, $46
; End of RORY_FACE_DETERMINED_OPTIMISED.Z80
