; RORY_TILESET_OPTIMISED.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Rory tileset
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 38
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Rory tiles", ROM0


rory_tileset:
DB $0F,$FF,$18,$F8,$30,$F0,$40,$C0
DB $41,$C1,$42,$C3,$62,$E3,$1C,$FF
DB $00,$FF,$00,$FF,$00,$FF,$01,$FF
DB $02,$FE,$05,$FD,$0B,$FA,$0B,$FA
DB $C0,$FF,$20,$3F,$20,$3F,$30,$3F
DB $98,$9F,$48,$CF,$88,$8F,$84,$87
DB $84,$87,$48,$CF,$9F,$9F,$00,$00
DB $40,$40,$A0,$A0,$D8,$58,$E0,$20
DB $09,$F9,$05,$FD,$08,$F8,$10,$F0
DB $20,$E0,$20,$E0,$10,$F0,$0C,$FC
DB $03,$FF,$00,$FF,$03,$FF,$04,$FC
DB $08,$F8,$11,$F1,$11,$F1,$23,$E3
DB $FC,$3C,$FC,$24,$DC,$A4,$D8,$C8
DB $73,$73,$01,$01,$00,$00,$0E,$0E
DB $11,$11,$C0,$C0,$FF,$FF,$23,$23
DB $DF,$FF,$00,$FF,$00,$FF,$F8,$FF
DB $01,$FF,$06,$FE,$08,$F8,$10,$F0
DB $10,$F0,$31,$F1,$41,$C1,$42,$C3
DB $82,$83,$84,$87,$C8,$CF,$04,$07
DB $12,$13,$2F,$2F,$DE,$D2,$3E,$32
DB $C0,$FF,$30,$3F,$08,$0F,$08,$0F
DB $C4,$C7,$64,$E7,$24,$E7,$3C,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$80,$FF,$40,$7F
DB $FE,$F2,$FE,$92,$EE,$92,$6C,$44
DB $38,$38,$00,$00,$00,$00,$00,$00
DB $01,$01,$03,$03,$FC,$FF,$13,$13
DB $F8,$F8,$0C,$FC,$0E,$FE,$3F,$FF
DB $40,$7F,$80,$FF,$60,$7F,$10,$1F
DB $10,$1F,$10,$1F,$10,$1F,$60,$7F
DB $80,$FF,$00,$FF,$00,$FF,$00,$FF
DB $80,$FF,$43,$7F,$3C,$3F,$F0,$FF
DB $45,$C7,$45,$C7,$8B,$8F,$8A,$8F
DB $0A,$0F,$0A,$0F,$33,$3F,$09,$0F
DB $08,$0F,$89,$8F,$71,$FF,$02,$FE
DB $06,$FE,$04,$FC,$04,$FC,$7E,$FE
DB $FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $C0,$FF,$3F,$3F,$10,$1F,$20,$3F
DB $20,$3F,$20,$3F,$10,$1F,$10,$1F
DB $83,$83,$80,$80,$80,$80,$40,$C0
DB $3F,$FF,$00,$FF,$00,$FF,$00,$FF
DB $09,$0F,$11,$1F,$20,$3F,$C0,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $FE,$FF,$FE,$FF,$FE,$FF,$FE,$FF
DB $02,$FF,$02,$FF,$02,$FF,$06,$FF
DB $09,$FF,$F9,$FF,$48,$CF,$48,$CF
DB $48,$CF,$48,$CF,$48,$CF,$89,$8F
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$FF,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$F0,$FF
DB $06,$06,$00,$00,$C0,$C0,$38,$F8
DB $07,$FF,$00,$FF,$00,$FF,$00,$FF
DB $08,$0F,$08,$0F,$08,$0F,$10,$1F
DB $E0,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$40,$FF
DB $A0,$FF,$20,$FF,$10,$FF,$10,$FF
DB $10,$FF,$08,$FF,$08,$FF,$08,$FF
DB $08,$FF,$08,$FF,$08,$FF,$10,$FF
DB $20,$FF,$C0,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $1F,$FC,$03,$FF,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $FF,$00,$FF,$80,$7F,$F0,$0F,$FE
DB $01,$FF,$00,$FF,$00,$FF,$00,$FF
DB $FC,$0F,$FE,$03,$FF,$01,$FF,$00
DB $FF,$C0,$3F,$F8,$07,$FF,$00,$FF
DB $00,$FF,$04,$FF,$8A,$FF,$CA,$7F
DB $F3,$3F,$E6,$3E,$E8,$38,$E8,$F8
DB $44,$7C,$47,$7F,$98,$FF,$60,$FF
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $7F,$FF,$7F,$C0,$7F,$C0,$7F,$C0
DB $3F,$E0,$3F,$E0,$3F,$E0,$3F,$E0
DB $C0,$FF,$E0,$3F,$F8,$1F,$FC,$07
DB $FF,$03,$FF,$00,$FF,$00,$FF,$00
DB $00,$FF,$00,$FF,$00,$FF,$00,$FF
DB $00,$FF,$80,$FF,$E0,$7F,$F0,$1F
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
rory_tileset_end: 
