; RORY_SWORD.Z80
;
; Tile Source File.
;
; Info:
;   Section              : rory_sword_sprite
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 16
;   Tiles                : 0 to 6
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "rory_sword_sprite", ROMX, BANK[1]

; Start of tile array.
rory_sword_sprite:
DB $03,$00,$03,$00,$06,$00,$06,$00
DB $06,$00,$07,$00,$07,$00,$1F,$00
DB $9F,$00,$CF,$00,$E7,$00,$73,$00
DB $30,$0D,$0B,$35,$0E,$31,$0E,$01
DB $1C,$00,$1C,$00,$30,$00,$30,$00
DB $30,$00,$F8,$00,$F8,$00,$FC,$48
DB $FC,$48,$FC,$4A,$F8,$16,$F0,$0E
DB $10,$EE,$F0,$EE,$10,$EE,$00,$EC
DB $03,$00,$1E,$00,$3E,$00,$7E,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $30,$CC,$70,$00,$78,$00,$7C,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $03,$00,$03,$00,$06,$00,$06,$00
DB $06,$00,$07,$00,$07,$00,$1F,$00
DB $1F,$00,$0F,$00,$07,$00,$03,$00
DB $00,$03,$01,$01,$00,$00,$01,$00
DB $1C,$00,$1C,$00,$30,$00,$30,$00
DB $30,$00,$F8,$00,$F8,$00,$FC,$48
DB $FC,$48,$FC,$48,$FC,$10,$F8,$00
DB $00,$F0,$F0,$80,$38,$C4,$1B,$E4
DB $30,$C0,$70,$00,$78,$00,$3C,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
rory_sword_sprite_end: 

; End of RORY_SWORD.Z80
