; RORY_IDLE_SPRITE.Z80
;
; Tile Source File.
;
; Info:
;   Section              : rory_idle_sprite
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 16
;   Tiles                : 0 to 3
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "rory_idle_sprite",ROMX,BANK[1]

; Start of tile array.
rory_idle_sprite:
DB $07,$00,$07,$00,$0C,$00,$0C,$00
DB $0C,$00,$0F,$00,$0F,$00,$3F,$01
DB $3F,$01,$1F,$01,$0F,$00,$07,$00
DB $00,$43,$BF,$43,$38,$43,$00,$43
DB $38,$00,$38,$00,$60,$00,$60,$00
DB $60,$00,$F0,$00,$F0,$00,$F8,$20
DB $F8,$20,$F8,$22,$F0,$42,$E0,$06
DB $00,$CE,$E0,$CE,$30,$CE,$10,$CC
DB $02,$01,$1E,$00,$3E,$00,$7E,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $40,$8C,$70,$00,$78,$00,$7C,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
rory_idle_sprite_end: 
; End of RORY_IDLE_SPRITE.Z80
