; RORY_INTRO_OPTIMISED.Z80
;
; Map Source File.
;
; Info:
;   Section       : ROM0
;   Bank          : 0
;   Map size      : 19 x 19
;   Tile set      : rory_tileset_optimised.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 43
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "Rory intro map", ROM0

rory_intro:
; Compressed data: 
DB $83, $55, $8B, $46, $87, $55, $8B, $46, $87, $55, 
DB $8B, $46, $87, $55, $8B, $46, $87, $55, $84, $46, 
DB $03, $2E, $30, $36, $38, $82, $46, $87, $55, $84, 
DB $46, $03, $2F, $31, $37, $39, $82, $46, $87, $55, 
DB $84, $46, $03, $32, $34, $3A, $3C, $82, $46, $87, 
DB $55, $09, $46, $52, $53, $54, $46, $33, $35, $3B, 
DB $3D, $4A, $81, $46, $87, $55, $09, $46, $4D, $4E, 
DB $4F, $50, $3E, $40, $44, $46, $4B, $81, $46, $87, 
DB $55, $83, $46, $05, $51, $3F, $41, $45, $47, $4C, 
DB $81, $46, $87, $55, $84, $46, $03, $42, $43, $48, 
DB $49, $82, $46, $87, $55, $8B, $46, $87, $55, $8B, 
DB $46, $87, $55, $8B, $46, $87, $55, $8B, $46, $87, 
DB $55, $8B, $46, $87, $55, $8B, $46, $87, $55, $8B, 
DB $46, $83, $55, $48