; RORY_FACE_OPTIMISED.Z80
;
; Map Source File.
;
; Info:
;   Section       : rory face map
;   Bank          : 0
;   Map size      : 20 x 18
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Tiles\Story-tiles\rory_face_tileset_optimised.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 46
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "rory face map", ROM0

rory_face:
; Compressed data: 
DB $C1, $29, $05, $62, $64, $67, $29, $6D, $6E, $8D, 
DB $29, $06, $63, $66, $68, $6A, $6F, $70, $72, $8C, 
DB $29, $06, $65, $6B, $69, $6C, $2C, $71, $73, $8C, 
DB $29, $06, $2E, $30, $36, $38, $3E, $40, $45, $8C, 
DB $29, $05, $2F, $31, $37, $39, $3F, $41, $8D, $29, 
DB $06, $32, $34, $3A, $3C, $42, $43, $46, $8C, $29, 
DB $06, $33, $35, $3B, $3D, $2C, $44, $47, $8D, $29, 
DB $04, $49, $4F, $51, $57, $59, $8D, $29, $06, $48, 
DB $4A, $50, $52, $58, $5A, $5F, $8C, $29, $06, $4B, 
DB $4D, $53, $55, $5B, $5D, $60, $8C, $29, $00, $4C, 
DB $83, $5C, $01, $5E, $61, $D6, $29, $D9
; End of RORY_FACE_OPTIMISED.Z80
