; STAGE_S1_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Stage_s1_tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 42
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Stage_s1_tiles",ROMX,BANK[1]

; Start of tile array.
Stage_s1_tiles:
DB $86,$FF,$06,$FF,$06,$FE,$86,$FF
DB $F0,$FF,$80,$FF,$7F,$80,$FF,$00
DB $00,$FF,$07,$F8,$23,$FC,$73,$FC
DB $F3,$FC,$78,$FF,$B8,$7F,$DC,$3F
DB $FE,$FF,$FE,$FF,$FC,$FF,$FC,$FF
DB $FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $F9,$06,$F9,$06,$F3,$0C,$63,$9C
DB $03,$FC,$01,$FE,$C0,$FF,$F8,$FF
DB $CF,$3F,$F7,$0F,$E7,$1F,$C6,$3F
DB $DC,$3F,$87,$7F,$07,$FF,$07,$FF
DB $F7,$FF,$F3,$8F,$61,$9F,$00,$FF
DB $3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $07,$F9,$07,$F9,$87,$F9,$E0,$FF
DB $C1,$FF,$03,$FF,$37,$FF,$77,$FF
DB $FC,$FF,$FE,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $07,$FF,$07,$FF,$E7,$FF,$F7,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $07,$FF,$1F,$E7,$1F,$E7,$1F,$E7
DB $01,$FF,$07,$FF,$0F,$FF,$3F,$FF
DB $FE,$FF,$FE,$FF,$3C,$FF,$CC,$3F
DB $EE,$1F,$F7,$0F,$99,$67,$01,$FF
DB $03,$FF,$0F,$FF,$3F,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $E3,$FF,$E3,$FF,$EF,$FF,$8F,$FF
DB $8F,$FF,$EF,$FF,$E3,$FF,$E3,$FF
DB $EF,$FF,$8F,$FF,$8F,$FF,$EF,$FF
DB $E3,$FF,$E3,$FF,$EF,$FF,$8F,$FF
DB $8F,$FF,$EF,$FF,$E3,$FF,$E3,$FF
DB $EF,$FF,$8F,$FF,$8F,$FF,$EF,$FF
DB $9B,$11,$1B,$91,$43,$91,$31,$93
DB $83,$33,$F7,$23,$43,$E7,$E9,$C7
DB $A1,$CF,$35,$CF,$6D,$CF,$89,$6F
DB $F5,$2F,$3D,$27,$47,$33,$B1,$13
DB $E5,$F7,$A3,$E7,$0D,$E3,$55,$E3
DB $5D,$E3,$59,$E7,$55,$EB,$5D,$EB
DB $49,$FF,$DD,$FB,$DF,$FB,$FB,$FF
DB $FB,$FF,$DD,$FF,$D5,$FF,$D5,$FF
DB $7D,$FF,$FD,$FF,$7D,$FF,$5D,$FF
DB $D5,$FF,$55,$FF,$5D,$FF,$D5,$FF
DB $D1,$FF,$D1,$FF,$D1,$FF,$D5,$FF
DB $CD,$FF,$E9,$FF,$E9,$FF,$E9,$FF
DB $D8,$FF,$BA,$FF,$BA,$FF,$FC,$FF
DB $D5,$FF,$D3,$FF,$E6,$FF,$2D,$FF
DB $AD,$FF,$B9,$FF,$F5,$FB,$BE,$F3
DB $AB,$F7,$ED,$F7,$E5,$FF,$E8,$F7
DB $7F,$FF,$DB,$FF,$5A,$FF,$5E,$FF
DB $FE,$FF,$AE,$FF,$EB,$FF,$6D,$FF
DB $B6,$FF,$FE,$FF,$F6,$FF,$B6,$FF
DB $B7,$FF,$FD,$FF,$F5,$FF,$B5,$FF
DB $F7,$FF,$FF,$FF,$F7,$FF,$F7,$FF
DB $F7,$FF,$FF,$FF,$F7,$FF,$F7,$FF
DB $FB,$FF,$EF,$FF,$ED,$FF,$FD,$FF
DB $ED,$FF,$ED,$FF,$FF,$FF,$FB,$FF
DB $FF,$FF,$0F,$07,$98,$00,$32,$CC
DB $88,$FF,$2D,$FE,$66,$F9,$DC,$F3
DB $33,$CF,$D8,$3F,$33,$FF,$E7,$FF
DB $DF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$F8,$F0,$15,$00,$B8,$06
DB $70,$8F,$4B,$BC,$35,$FB,$0F,$FF
DB $FF,$FF,$0F,$07,$C0,$00,$AC,$50
DB $00,$FF,$B9,$FF,$CF,$FF,$FF,$FF
DB $FF,$FF,$03,$0B,$2D,$11,$15,$F1
DB $4B,$BB,$7F,$FF,$FF,$FF,$FF,$FF
DB $3F,$FF,$7F,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$07,$03,$31,$00,$A4,$5B
DB $69,$F7,$8E,$FF,$3F,$FF,$FF,$FF
DB $FF,$FF,$F0,$E0,$19,$00,$4C,$33
DB $11,$FF,$B4,$7F,$66,$9F,$3B,$CF
DB $CC,$F3,$1B,$FC,$CC,$FF,$E7,$FF
DB $FB,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$1F,$0F,$A8,$00,$1D,$60
DB $0E,$F1,$D2,$3D,$AC,$DF,$F0,$FF
DB $FC,$FF,$FE,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$F0,$E0,$03,$00,$35,$0A
DB $00,$FF,$9D,$FF,$F3,$FF,$FF,$FF
DB $FF,$FF,$C0,$D0,$B4,$88,$A8,$8F
DB $D2,$DD,$FE,$FF,$FF,$FF,$FF,$FF
DB $00,$FF,$00,$FF,$FF,$00,$FF,$00
DB $FF,$00,$00,$FF,$80,$7F,$FF,$00
DB $F0,$CF,$F0,$CF,$FF,$F0,$FF,$F8
DB $FF,$FC,$FE,$FF,$FF,$FF,$FF,$FF
DB $03,$FF,$03,$FF,$FF,$0F,$FF,$1F
DB $FF,$3F,$7F,$FF,$7F,$FF,$FF,$7F
DB $FF,$FF,$FF,$FF,$FF,$FF,$FE,$FF
DB $FE,$FF,$FF,$FE,$FE,$F9,$FF,$F0
DB $80,$7F,$C0,$3F,$FF,$00,$80,$7F
DB $80,$7F,$FF,$00,$00,$FF,$00,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$7F,$FF
DB $7F,$FF,$FF,$3F,$0F,$FF,$07,$FF
Stage_s1_tiles_end:

; End of STAGE_S1_TILES.Z80
