; HUD.Z80
;
; Map Source File.
;
; Info:
;   Section       : HUD
;   Bank          : 1
;   Map size      : 20 x 3
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Fonts\font.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.8

 SECTION "HUD", ROMX, BANK[1]

HUD:
    DB $0F,$0B,$00,$18,$04,$11,$29,$29,$29,$29
    DB $29,$29,$29,$29,$29,$29,$12,$13,$06,$29
    DB $29,$29,$29,$29,$29,$29,$29,$29,$29,$29
    DB $29,$29,$29,$29,$29,$29,$29,$29,$29,$29
    DB $12,$02,$0E,$11,$04,$29,$29,$29,$29,$29
    DB $29,$29,$29,$29,$29,$29,$29,$24,$29,$29
HUD_END:

; End of HUD.Z80
