; HUD_SYMBOLS.Z80
;
; Tile Source File.
;
; Info:
;   Section              : HUD SYMBOLS
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 1
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "HUD SYMBOLS", ROMX, BANK[1]

; Start of tile array.
HUD_SYMBOLS:
    DB $00,$FF,$7F,$FF,$7F,$E0,$7F,$F0
    DB $7F,$FC,$7F,$FE,$7F,$FF,$7F,$FF
    DB $7F,$FF,$7F,$FE,$7F,$FC,$7F,$F0
    DB $7F,$E0,$7F,$FF,$7F,$FF,$00,$FF
    DB $00,$FF,$FE,$FF,$FE,$7F,$FE,$1F
    DB $FE,$0F,$FE,$07,$FE,$07,$FE,$07
    DB $FE,$07,$FE,$07,$FE,$0F,$FE,$1F
    DB $FE,$7F,$FE,$FF,$FE,$FF,$00,$FF
    DB $18,$FF,$18,$FF,$18,$FF,$18,$FF
    DB $18,$FF,$18,$FF,$18,$FF,$18,$FF
    DB $C6,$FF,$C6,$FF,$C6,$FF,$C6,$FF
    DB $C6,$FF,$C6,$FF,$C6,$FF,$C6,$FF
    DB $31,$FF,$31,$FF,$31,$FF,$31,$FF
    DB $31,$FF,$31,$FF,$31,$FF,$31,$FF
    DB $8C,$FF,$8C,$FF,$8C,$FF,$8C,$FF
    DB $8C,$FF,$8C,$FF,$8C,$FF,$8C,$FF
    DB $63,$FF,$63,$FF,$63,$FF,$63,$FF
    DB $63,$FF,$63,$FF,$63,$FF,$63,$FF
    DB $1F,$FF,$1F,$FF,$1F,$FF,$1F,$FF
    DB $1F,$FF,$1F,$FF,$1F,$FF,$1F,$FF
    DB $7F,$FF,$7F,$FF,$7F,$FF,$7F,$FF
    DB $7F,$FF,$7F,$FF,$7F,$FF,$7F,$FF
    DB $8C,$FF,$8C,$FF,$8C,$FF,$8C,$FF
    DB $8C,$FF,$8C,$FF,$8C,$FF,$8C,$FF
    DB $8F,$FF,$8F,$FF,$8F,$FF,$8F,$FF
    DB $8F,$FF,$8F,$FF,$8F,$FF,$8F,$FF
    DB $3F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
    DB $3F,$FF,$3F,$FF,$3F,$FF,$3F,$FF
    DB $C6,$FF,$C6,$FF,$C6,$FF,$C6,$FF
    DB $C6,$FF,$C6,$FF,$C6,$FF,$C6,$FF
    DB $C7,$FF,$C7,$FF,$C7,$FF,$C7,$FF
    DB $C7,$FF,$C7,$FF,$C7,$FF,$C7,$FF
HUD_SYMBOLS_END:

; End of HUD_SYMBOLS.Z80
