; STAGE_S2.Z80
;
; Map Source File.
;
; Info:
;   Section       : Stage_s2
;   Bank          : 1
;   Map size      : 20 x 18
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Tiles\Game-tiles\Stage-1\stage_s1.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 128
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "Stage_s2", ROMX, BANK[1]

Stage_s2:
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AD
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AD
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AD
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AD
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AD
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AD
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $89,$80,$81,$86,$80,$81,$86,$80,$81,$86
DB $80,$81,$86,$80,$81,$86,$80,$81,$86,$80
DB $8A,$83,$84,$85,$83,$84,$85,$83,$84,$85
DB $83,$84,$85,$83,$84,$85,$83,$84,$85,$83
DB $8B,$87,$88,$AB,$87,$88,$AB,$87,$88,$AB
DB $87,$88,$AB,$87,$88,$AB,$87,$88,$AB,$87
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
DB $AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB,$AB
Stage_s2_end: 

; End of STAGE_S2.Z80
