; MUSHROOM_ATTACK.Z80
;
; Map Source File.
;
; Info:
;   Section       : ROM0
;   Bank          : 0
;   Map size      : 32 x 19
;   Tile set      : C:\Users\Jelli\OneDrive\Desktop\Rabbit_Knight\Backgrounds\Scenes\Mushroom_attack\mushroom_attack_optimized.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 43
;   Split data    : No
;
; This file was generated by GBMB v1.8

SECTION "Mushroom attack map", ROM0

mushroom_attack:
; Compressed data: 
DB $FF, $2F, $9F, $2F, $AD, $2E, $01, $42, $43, $99, 
DB $2E, $01, $4B, $4D, $81, $2E, $02, $3E, $40, $5D, 
DB $92, $2E, $02, $64, $65, $66, $82, $2E, $05, $4C, 
DB $4E, $4A, $2E, $3F, $41, $93, $2E, $10, $60, $62, 
DB $5C, $5E, $53, $55, $4F, $51, $46, $48, $3A, $3C, 
DB $36, $38, $30, $32, $34, $8E, $2E, $10, $61, $63, 
DB $5D, $5F, $54, $56, $50, $52, $47, $49, $3B, $3D, 
DB $37, $39, $31, $33, $35, $91, $2E, $0C, $6D, $6E, 
DB $6F, $5A, $5B, $57, $59, $44, $45, $69, $6A, $6B, 
DB $6C, $95, $2E, $02, $68, $67, $58, $FF, $2E, $D2, 
DB $2E, $49
